# entrypoint: python app.py
env: flex

runtime_config:
  python_version: 2

# instance_class: F1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2